name: CI (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
      -
        name:
        run: |
          mkdir ../panel
          cp -r ./* ../panel
          pushd ..
          zip -r install.zip panel -x panel/update.lst
          zip -r update.zip panel -x@panel/update.lst
          popd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.version }}
          tag_name: "v${{ github.event.inputs.version }}"
          files: |
            ../install.zip
            ../update.zip
