name: CI

on:
  push:
    branches:
      - '7.9.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3

      -
        name:
        run: |
          mkdir ../panel
          cp -r ./* ../panel
          pushd ..
          zip -r install.zip panel -x panel/update.lst
          zip -r update.zip panel -x@panel/update.lst
          popd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'PagodaPanel v7.9.3'
          tag_name: "v7.9.3"
          files: |
            ../install.zip
            ../update.zip
