name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: dev
      -
        name:
        run: |
          mkdir ../panel
          cp -r ./* ../panel
          pushd ..
          zip -r install.zip panel -x panel/update.lst
          zip -r update.zip panel -x@panel/update.lst
          popd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "7.9.2-dev"
          tag_name: "v7.9.2-dev"
          prerelease: true
          files: |
            ../install.zip
            ../update.zip